# Arquivo de configuração para deploy da API no Render.com
# Conectando a um banco de dados externo (Supabase).

services:
  # O serviço de banco de dados foi REMOVIDO, pois usaremos o Supabase.

  # ------------------- Serviço da API Web -------------------
  - type: web # web indica um serviço que recebe tráfego HTTP
    name: portfolio-api # Nome da sua API no Render
    runtime: node # Ambiente de execução
    plan: free # Plano gratuito. O serviço "dorme" após inatividade.
    region: oregon # Escolha a região mais próxima do seu banco Supabase se possível.

    # Comandos que o Render executa para preparar sua aplicação
    buildCommand: 'npm install && npx prisma generate && npx prisma migrate deploy'

    # Comando para iniciar o servidor após o build
    startCommand: 'npm start'

    # Variáveis de ambiente para a sua API
    envVars:
      - key: NODE_ENV
        value: production
      # IMPORTANTE: A variável DATABASE_URL será adicionada manualmente no dashboard do Render.
